### PR TITLE
The /fetch endpoint can be authenticated via session or via HTTP basic

### PR DESCRIPTION
**Pull request by thomasbrueggemann**
I wasn't able to "pull the /fetch endpoint under the Django RestFramework" as proposed in the issue #178 but found a great way to check via a Mixin if the session or HTTP Basic auth was used to call the /fetch and /push endpoint.

The Django RestFramework magic is definitly to much to read into in reasonable time.
What do you think about it, @danielquinn ?

### CODE REVIEW

**Comment by danielquinn** [comment]
Porting the FetchView to DRF would probably be more elgant, but I'm not in a hurry to make things difficult just for two views.  I'm fine with this setup, so long as you can get it to conform to pep8 (that's they the check failed: you've got a 3-space indent in your class there).

So, if you can fix that, I'll merge the change.

**Comment by thomasbrueggemann** [comment]
Working on the pep8 fix right now.

**Comment by thomasbrueggemann** [comment]
Done.

**Comment by danielquinn** [comment]
Nice!  Merged!

**Comment by thomasbrueggemann** [comment]
Awesome, thanks!

**Pull request merged**
