### PR TITLE
Better interface when we have many tags

### PR DESCRIPTION
**Pull request by sbrunner**
=>
tags

### CODE REVIEW

**Comment by boringusername99** [comment]
This looks like a great add! I'm surprised no one else has mentioned sorting of tags to be alphabetical, both on this selection UI and in the document sidebar. Did you consider this enhancement at all?

**Comment by sbrunner** [comment]
+1 to sort tags alphabetical, I should fond how to do that and purpose a new pull request :-)

**Comment by danielquinn** [comment]
This is an excellent addition, thank you!

As per @boringusername99's suggestion, I've also added a default ordering for tags.

**Comment by ddddavidmartin** [comment]
I might be a bit slow, how do you get to this new tags menu? Or is it only available after a certain number of tags? Thanks!

**Comment by danielquinn** [comment]
The new menu should appear as soon as you restart the `runserver` regardless of the number of tags you've got.

**Comment by ddddavidmartin** [comment]
Ah yes, thanks! It shows when changing the properties of a document. I thought this would change how documents can be filtered with tags.

**Pull request merged**
