### PR TITLE
Fix modifying the GID under alpine

### PR DESCRIPTION
**Pull request by pitkley**
This fixes issue #306.

### CODE REVIEW

**Comment by pitkley** [comment]
I have only just seen #311. I've updated my PR to include the typos @ChromoX fixed -- thanks for that!

Pro @ChromoX solution: no additional package required.
Pro from my solution: no need to delete and recreate both the user and the group.

I don't care which one gets merged, both should be fine! :slightly_smiling_face:

**Comment by ChromoX** [comment]
I prefer your commit as it's obvious to what the intention of the code is.

**Comment by pitkley** [comment]
Okay, thanks for the consensus. I think there is still an issue with mapping the UID, I'll push a fix shortly. I'll ping you @danielquinn once the PR is ready!

**Comment by pitkley** [comment]
I have updated the PR to use `usermod` since it is available now that we have `shadow` installed (thanks @ChromoX!).

I have also renamed the computed `USERMAP_UID` and `USERMAP_GID` to `USERMAP_NEW_UID` and `USERMAP_NEW_GID` respectively. I hope this makes the logic more clear.

This PR is ready from my side @danielquinn!

**Comment by danielquinn** [comment]
Hooray!  Thanks to both of you for your hard work (and collaboration) on this!

**Pull request merged**
