### PR TITLE
Extends the regex to find dates in documents as reported by @isaacsando

### PR DESCRIPTION
**Pull request by BastianPoe**
This extends the regex to find dates in documents as reported in #301 

@isaacsando, please try out and report back

### CODE REVIEW

**Comment by ddddavidmartin** [comment]
One thought on the date matching in general:
It would be great if the detected date was printed in the log output. This would make it easier to sanity-check that the correct date was applied, and to find the document again if not. For example I had it happen that my birth date was the first in the document and it was stored under that.

Feel free to ignore if this is out of scope of this pull request.

**Comment by BastianPoe** [comment]
@ddddavidmartin please have a look if the change matches want you wanted.

**Comment by ddddavidmartin** [comment]
@BastianPoe, I have not had a chance yet to actually run this branch, but looking at https://github.com/danielquinn/paperless/pull/302/commits/c74bb84c8321a03feb5e2a128bb8764d5795f783 this is exactly what I was asking for. Thanks!

**Comment by danielquinn** [comment]
I'm inclined to merge this.  @BastianPoe & @isaacsando you cool with that?

**Comment by danielquinn** [comment]
I just saw that @isaacsando gave this the thumbs up in #301 so I'm merging it now :-)

**Pull request merged**
