### PR TITLE
New imported documents list

### PR DESCRIPTION
**Pull request by CkuT**
See #319

### CODE REVIEW

**Comment by CkuT** [comment]
This is a WIP : some tests are not written and other may not pass

**Comment by CkuT** [comment]
Oddly, some tests do not pass if the variable `PAPERLESS_SHARED_SECRET` is not defined.

I think it comes from this part of code : https://github.com/danielquinn/paperless/blob/master/src/documents/mail.py#L46-L49

**Comment by danielquinn** [comment]
This all looks good to me.  Are you cool with me merging it, or did you want to discuss things more on #319?

**Comment by danielquinn** [comment]
Also, regarding the test failure, I re-ran the tests locally and couldn't reproduce the error you mentioned here.  Regardless, I removed the line you pointed too as it was well past time to do so anyway.  Out of curiosity, how are you running the tests exactly?  This is how I do it:

```bash
cd src/
pytest
```

...either that or using tox to be thorough:

```bash
cd src/
tox
```

**Comment by CkuT** [comment]
You can merge it. (unless somebody thinks of an improvement)

I also run my tests like you do it : 
```bash
cd src/
pytest
```

It's odd, but no more problem if you removed the code ;)

**Comment by danielquinn** [comment]
Sweet!  Thanks for your work on this :-)

**Pull request merged**
