### PR TITLE
Refactor file info extraction

### PR DESCRIPTION
**Pull request by tikitu**
Here's the useful bit of my (slow) movement towards fixing #51, before that became unnecessary.

There are some failing tests: they're edge cases that I turned up in the regex handling. I think everything should work as it used to, but I haven't given it *very* close attention: it turns out my lifestyle (small children; day job) is not really compatible with the pace of development you're keeping up here.

### CODE REVIEW

**Comment by danielquinn** [comment]
This is a big PR, so I'll need some time to look over it.  Let me get back to you in a couple days?

**Comment by danielquinn** [comment]
I'm sorry this is taking so long, but I have been poking at it locally.  Don't think I've forgotten!

**Comment by danielquinn** [comment]
Finally merged!  Sorry it took so long, but I wanted to (a) account for the test failures, and (b) add support for including the date in the file name.

**Comment by tikitu** [comment]
Hey, great!

**Pull request merged**
